### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by weverton0800** [vmakeev/huawei_mesh_router#43]
Este erro originou-se de uma integração personalizada.

Logger: custom_components.huawei_mesh_router.update_coordinator (Huawei Router)
Source: custom_components/huawei_mesh_router/update_coordinator.py:271
Integration: Huawei Mesh Router (documentation, issues)
First occurred: 13:00:28 (4 occurrences)
Last logged: 17:47:55

Can not update repeater state Can not perform GET request at api/ntwk/repeaterinfo cause of TimeoutError(); code: -3, category: request_error
Can not update connected devices: TimeoutError()
Can not update router info: TimeoutError()
Can not update router info: Can not perform GET request at api/system/deviceinfo cause of TimeoutError(); code: -3, category: request_error

**Comment by vmakeev** [comment]
Hi!

> Timeout error()

It looks like an unstable or intermittent connection between the Home Assistant server and the router

> First occurred: 13:00:28 (4 appearances)
> Last registered: 17:47:55

Four errors in almost 5 hours also indirectly hint that the problem is not permanent.


However, I can't rule out an error in the integration itself, сan I ask you to send debug logs of integration? 
To enable them, you will need to make changes to `configuration.yaml` and restart HA.

Changes in configuration.yaml:

```
logger:
  .....
  logs:
    custom_components.huawei_mesh_router: debug
```

You may need to click the "load full logs" button to see the debug messages

**Comment by vmakeev** [comment]
@weverton0800 Do I understand correctly that the problem has self-eliminated?

**Comment by weverton0800** [comment]
the glitch just stopped happening
