### ISSUE TITLE
Initialization fails with HA 2023-06-X

### ISSUE THREAD

**Issue by bjoernwedi** [vmakeev/huawei_mesh_router#52]
ogger: homeassistant.config_entries
Source: custom_components/huawei_mesh_router/__init__.py:86
Integration: Huawei Mesh Router ([documentation](https://github.com/vmakeev/huawei_mesh_router), [issues](https://github.com/vmakeev/huawei_mesh_router/issues))
First occurred: 15. Juni 2023 um 12:32:50 (4 occurrences)
Last logged: 09:47:06

Error setting up entry Huawei Router for huawei_mesh_router
Error setting up entry (.....) for huawei_mesh_router
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/huawei_mesh_router/__init__.py", line 86, in async_setup_entry
    hass.config_entries.async_setup_platforms(
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by vmakeev** [comment]
Hello!

It looks like you are using the component version `0.8.4` or lower. This version use the Home Assistant function, which was removed in Home Assistant `2023.3`.

Please try to update the component to the [latest version](https://github.com/vmakeev/huawei_mesh_router/releases/latest), this should solve the problem. The process of installing or updating the component is described [here](https://github.com/vmakeev/huawei_mesh_router#installation)

**Comment by bjoernwedi** [comment]
I used the master.
Am I supposed to use the feature branch for 2023?

**Comment by vmakeev** [comment]
Judging by the title of the message, you are using the version of Home Assistant `2023.6`, is that correct?

Judging by the error text (`File "/config/custom_components/huawei_mesh_router/init.py", line 86, in async_setup_entry
hass.config_entries.async_setup_platforms(`), you are using the component version `0.8.4` or lower, is that correct? Since in more recent versions there is no such code in the `init.py`.

The code that the error message says was in version 0.8.4 ([link to the old code](https://github.com/vmakeev/huawei_mesh_router/blob/v0.8.4/custom_components/huawei_mesh_router/__init__.py#L86), [link to the changes in MR](https://github.com/vmakeev/huawei_mesh_router/pull/37/files#diff-cafd7d18f6ccefbe1afeeb144ec6c1ee9ce5d23761a250db831c8c1accb50a34L93))

In newer versions, including the current master, the method `async_setup_platforms` is no longer called ([link to the same place in the master](https://github.com/vmakeev/huawei_mesh_router/blob/master/custom_components/huawei_mesh_router/__init__.py#L95))

Also make sure that you have completely restarted the Home Assistant after updating the component.

Can you specify which versions of Home Assistant and component you have installed?

**Comment by vmakeev** [comment]
@bjoernwedi is the problem still present? I want to help, but without your answers I have no such opportunity.

**Comment by vmakeev** [comment]
can I assume that the problem has been fixed after the update?
