### ISSUE TITLE
Switches unavailable after update

### ISSUE THREAD

**Issue by mlhyyl** [vmakeev/huawei_mesh_router#54]
I hadn't updated for a long time but once I did to the latest release, I'm no longer able to use the switches which would block or enable access to domains for specific devices. Despite returning to previous versions, switches remain disabled. I have a Huawei WiFi AX3 router, and messaages I found in the logs are as follows:

2023-07-21 22:32:00.086 DEBUG (MainThread) [custom_components.huawei_mesh_router.client.coreapi (192.168.1.1)] No csrf data found in the response
2023-07-21 22:32:00.086 DEBUG (MainThread) [custom_components.huawei_mesh_router.client.utils] Feature 'feature_wifi_80211r' is not available

...

2023-07-21 22:32:00.630 WARNING (MainThread) [custom_components.huawei_mesh_router.update_coordinator (Huawei Router)] Can not update switches: AttributeError('URL_FILTER')

**Comment by vmakeev** [comment]
Hi!

Can you tell me which version of the component you had before the update?

**Comment by mlhyyl** [comment]
I upgraded from v0.8.4.1 to v0.8.7.1.

I was able to resolve it by 

- removing the router in the integration,
- then the integration itself, 
- and removed Huawei entries in the core files located within the .storage folder
- also deleted the huawei_mesh file there
- Re-installed the integration

This time it worked.

**Comment by vmakeev** [comment]
Yes, during refactoring I made a [mistake in the class name](https://github.com/vmakeev/huawei_mesh_router/pull/51/files#diff-ee79878cda99ff55abab062ecbce10c7e46379517e46a2f3eff2ba65a6a26660R696) (I should have used `EmulatedSwitch.URL_FILTER` instead of `Switch.URL_FILTER`), it really affected version 0.8.7.1

In the next update (after the release of Home Assistant 2023.8) I will fix this behavior, thank you for your message

**Comment by vmakeev** [comment]
@mlhyyl [this pre-release](https://github.com/vmakeev/huawei_mesh_router/releases/tag/v0.9.0-rc1) should fix the problem
