### ISSUE TITLE
Cannot connect to Huawei WS7100

### ISSUE THREAD

**Issue by interkelstar** [vmakeev/huawei_mesh_router#59]
I'm trying to integrate with my [Huawei WiFi AX3 Dual-core](https://consumer.huawei.com/en/routers/ax3-dual-core/) WS7100

It is set up on 192.168.2.1

I can easily go by that address, type my password and log in.
But providing the same password, url default username admin and default port results for me in "Can not authenticate." message.

**Comment by vmakeev** [comment]
Hi!
Is your Home Assistant server connected directly to the AX3 router?

**Comment by vmakeev** [comment]
Actually, I use a similar connection scheme and also have to solve a number of issues :) 
 
My Home Assistant server is connected to a Mikrotik router. Huawei Mesh 3 routers are also connected to the same router.

Without using a clever trick, I would also not have access to the Huawei router from Home Assistant (the Huawei router perceives the Home Assistant server as something in the WAN, and, accordingly, does not allow access to admin panel).

The tricky trick is that the Raspberry Pi 3 is connected to the Huawei router, on which the reverse proxy server is configured (HAProxy, but you can use anything). The port forwarding is configured on the router itself so that requests from the "WAN" (in fact, from the Mikrotik router and other devices, including the smart home server) are redirected to the Raspberry Pi. <image>

![image](https://github.com/vmakeev/huawei_mesh_router/assets/13693034/e4a0ac3f-9e5d-4723-be42-c079de880f5d)

HAProxy on Raspberry Pi redirects incoming requests to it back to the Huawei router, but this time the router already believes that these requests are coming from a trusted LAN network, and allows access to admin panel.

When setting up integration, you need to specify the address of the Huawei router from the point of view of the network in which the Home Assistant server itself is located.

So, for example, my Huawei router has a LAN address of 192.168.3.1, but in the network to which the Home Assistant server is connected, its WAN address is 192.168.0.42.

In the component configuration, I will have to specify exactly 192.168.0.42.

Visually, the connection diagram looks like this: 

![image](https://github.com/vmakeev/huawei_mesh_router/assets/13693034/50ac6a9b-c1e4-460c-a612-82a765f54e59)


Part of the HAProxy configuration: 

```
frontend http-80
  mode http
  bind *:80

  acl IsMeshRouter hdr_reg(host) ^mesh\.router\.home$ # Home DNS name
  acl IsMeshRouter hdr_reg(host) ^192\.168\.0\.42$     # WAN router address
  acl IsMeshRouter hdr_reg(host) ^192\.168\.3\.1$      # LAN router address (not required)
  
  use_backend Mesh if IsMeshRouter


backend Mesh
  mode http
  balance leastconn
  http-request set-header Host 192.168.3.1 # Strongly required!
  server router 192.168.3.1:80
```


Yes, this interaction scheme looks somewhat cumbersome, but, unfortunately, the configuration capabilities of Huawei routers are very limited. An alternative option would be to connect the smart home server directly to the Huawei router (to its internal LAN network).
